### ISSUE TITLE
Support for self-closing elements

### ISSUE THREAD

**Issue by astro** [horazont/rxml#4]
While technically not required, this would be a feature *nice to have* in the future.

I wish for the Encoder to emit self-closing tags when there are zero child nodes.

**Comment by horazont** [comment]
The question is whether the Encoder is supposed to handle it on its own, or whether collaboration by the caller should be required.

In the former case, that means that we'll an explicit "flush" function: It would not be possible to completely write an element header just based on the header item. Only when the next item is encoded, the tag can be completed (if the next item is the closing tag, as `/>`, otherwise as `>` followed by the serialisation of the next item).

In the latter case, we'd have to extend the `Item` enum to cover that case, by adding a separate head tag variant which closes the element right away.

What do you think would be a more useful API?

**Comment by astro** [comment]
Actually we could change semantics a bit without breaking API at all by representing self-closure with `ElementFoot` instead of `ElementHeadEnd`. Would this require buffering much?

**Comment by horazont** [comment]
@astro You are completely right, that would work.

**Comment by horazont** [comment]
Opened #6, feedback welcome.
